### ISSUE TITLE
Monitoring/Alerting/Logging Epic

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#325]
Logging:
- [x] ID Minter:  Log failures
- [x] Ingestor:  Log failures
- [x] API: Log requests

Monitoring:
- [x] Visibility of service status: 
  - https://github.com/wellcometrust/platform-api/pull/397
  - ^ Add UI to JSON view
- [x] Visibility of dynamo capacity
- [x] Report counts in reindexer and transformer accurately.
- [x] Ingestor; Add metrics for items ingested: https://github.com/wellcometrust/platform-api/pull/383
- [x] ID Minter; Add metrics for IDs minted: https://github.com/wellcometrust/platform-api/pull/389
- [x] API: Request time/status metrics.
- [x] Notification of failed deploys: See  https://github.com/wellcometrust/platform-api/issues/397
- [x] Monitoring cluster hosts status (disk/memory/cpu): https://github.com/wellcometrust/platform-infra/pull/107
- [x] Monitoring container status (disk/memory/cpu): https://github.com/wellcometrust/platform-infra/pull/107

Alerts:
- [x] ID Minter DLQ > 0
- [x] ES Ingest DLQ > 0 
- [ ] ID Minter Queue Size > n
- [ ] ES Ingest Queue Size > n
- [ ] MiroData: Dynamo R/W exceeded
- [ ] Identifiers: Dynamo R/W exceeded
- [ ] ReindexTracker: Dynamo R/W exceeded
- [ ] Dynamo Stream Tables!
- [ ] Transformer failed to process a record

Alerts Visibility:
- [ ] Slackbot
- [x] Dashboards reporting counts in pipeline / API request status / frequency https://github.com/wellcometrust/platform-api/pull/403 https://github.com/wellcometrust/platform-api/pull/422

**Comment by kenoir** [comment]
Related: https://github.com/wellcometrust/platform-api/pull/303

**Comment by kenoir** [comment]
Closing!

**Comment by pollecuttn** [comment]
@kenoir There are unchecked checkboxes on this still for alerts - do we not need to worry about those? Why are we not worrying about them? Ta!

**Comment by kenoir** [comment]
Not for now. We're done as far as proactive alerting is concerned. I think there's more value in adding further alerts as we see problems.
