### ISSUE TITLE
nginx should deploy like service containers

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform-api#513]
Follow up action from incident retro:

- [x] New nginx images are pushed by Travis, not by hand (#515)
- [x] nginx images are tagged with a commit hash and a variant name, not just the variant name (#550)
- [x] Image tags are pushed to S3 like our other applications (#552)
- [x] Terraform uses the image tags in task definitions

**Comment by alexwlchan** [comment]
Related: #483.

**Comment by alexwlchan** [comment]
Closing for now, and I‘ll open other tickets if we see new problems.
